#!/usr/bin/env python2.7

import os
from flask import Flask

app=Flask(__name__)

if __name__=='__main__':
    app.debug=True
    app.secret_key=os.urandom(64)
    app.run(host='127.0.0.1',port=1338)
